# Generated by Django 5.0.4 on 2024-09-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='verifyemail',
            name='profile_image',
        ),
    ]
