# Generated by Django 5.0.4 on 2024-09-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='include_ac',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
