# Generated by Django 5.0.4 on 2024-09-22 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_include_ac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='extra_bed_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='person_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_instance',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookingRoomInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_bed_count', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.booking')),
                ('room_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roominstance')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room_instances',
            field=models.ManyToManyField(through='room.BookingRoomInstance', to='room.roominstance'),
        ),
    ]
