# Generated by Django 5.0.4 on 2024-09-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_profile_image_and_more'),
        ('room', '0003_remove_booking_extra_bed_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.user'),
        ),
    ]
