# Generated by Django 4.0 on 2024-09-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_instances',
            field=models.ManyToManyField(through='room.BookingRoomInstance', to='room.RoomInstance'),
        ),
    ]
